slides: []
html_captions: ''
options:
    theme: 'default'
    image_style: 0
    image_style_slide: 'large'
    image_style_thumb: 'thumbnail'
    random_start: 1
    start_slide: 0
    effect: 'random'
    slices: 15
    box_columns: 8
    box_rows: 4
    animation_speed: 500
    pause_on_hover: 1
    directional_navigation: 1
    next_text: 'Next'
    previous_text: 'Prev'
    control_navigation: 1
    control_nav_thumbs: 0
    manual_advance: 0
    pause_time: 3000
