<?php
// $Id$

/**
 * @file
 * Demonstrates use of the Form API.
 *
 * For a full list of elements and attributes, see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/7
 */

/**
 * Implements hook_menu().
 */
function input_menu() {
  $items['input/examples'] = array(
    'title' => 'Form API examples',
    'description' => 'Example of using the Form API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('input_simple_form'),
    'access callback' => TRUE,
  );
  $items['input/thanku'] = array(
    'title' => 'Lead Successfully Registered Thank You.',
    'description' => 'Lead Successfully Registered Thank You.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('thanku_message'),
    'access callback' => TRUE,
  );
  return $items;
}
/**
 * Thanku massage.
 */
function thanku_message($form, &$form_submit) {
  $build = array(
    'header_text' => array(
      '#type' => 'markup',
      '#markup' => '<p>' . t('will you get back to you shortly.') . '</p>',
    ),    
  );
  return $build;
}

/**
 * A simple form.
 */
function input_simple_form($form, &$form_submit) {
  $form['color'] = array(
    '#title' => t('Favorite color'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('What is your favorite color? Blue? No, wait-'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Implements hook_form_alter().
 *
 * To find the $form_id, you can ether add an echo $form_id; to print
 * a list of ids to the browser, or use Firebug to inspect the element and
 * conver the 'id' of the form to use underscores.
 */
function input_form_alter(&$form, &$form_state, $form_id) {
  //dsm($form_id);
  switch ($form_id) {
    case 'ezone_leads_node_form':
      dsm($form);
      $form['actions']['submit']['#submit'][] = 'input_node_submit_page_ezone';
      break;
  }
  return;
}

function input_node_submit_page_ezone($form, &$form_state) {
  $form_state['redirect'] = 'input/thanku';
}