<?php
// $Id$

/**
 * @file
 * Demonstrates use of the Form API.
 *
 * For a full list of elements and attributes, see:
 * http://api.drupal.org/api/drupal/developer--topics--forms_api_reference.html/7
 */

/**
 * Implements hook_menu().
 */
function lmsleadform_menu() {
  $items['lmsleadform/examples'] = array(
    'title' => 'Form API examples',
    'description' => 'Example of using the Form API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lmsleadform_simple_form'),
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * A simple form.
 */
function lmsleadform_simple_form($form, &$form_submit) {
  $form['color'] = array(
    '#title' => t('Favorite color'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('What is your favorite color? Blue? No, wait-'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

/**
 * Implements hook_form_alter().
 *
 * To find the $form_id, you can ether add an echo $form_id; to print
 * a list of ids to the browser, or use Firebug to inspect the element and
 * conver the 'id' of the form to use underscores.
 */
function lmsleadform_form_alter(&$form, &$form_state, $form_id) {
  dsm($form_id);
  switch ($form_id) {
    case 'ezone_leads_node_form':
      //dsm($form);
      //$form['actions']['submit']['#submit'][] = 'input_node_submit_page_ezone';
      break;
  }
  return;
}